name:                elm-syntax
version:             0.2.0.0
github:              "folq/elm-syntax"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2019 Olle Fredriksson"
tested-with:         GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.3

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Elm syntax and pretty-printing
category:            Elm, Compiler, Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/folq/elm-syntax#readme>

dependencies:
- base >= 4.7 && < 5
- bound >= 2.0.0
- deriving-compat >= 0.5
- prettyprinter >= 1.2.1
- protolude >= 0.2.3
- text >= 1.2.0
- unordered-containers >= 0.2.8

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

library:
  source-dirs: src

tests:
  elm-syntax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-syntax
